name: auto-format
run-name: Ensuring code style maintained
on: 
  pull_request:
    types:
    - closed
    branches:
      - master
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: prettier
        run: |
          npx prettier --write game/
      - name: Check for modified files
        id: git-check
        run: |
          echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Dylan'\''s CI Autoformatter'
          git commit -am "Automated changes by prettier"
          git push
